// <auto-generated />
using FooddonationManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FooddonationManagementSystem.Migrations
{
    [DbContext(typeof(FooddonationManagementSystemContext))]
    [Migration("20220913065817_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FooddonationManagementSystem.Models.SchoolModule", b =>
                {
                    b.Property<int>("DonarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DonarName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VegOrNonVeg")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DonarId");

                    b.ToTable("SchoolModule");
                });
#pragma warning restore 612, 618
        }
    }
}
